### ISSUE TITLE
Start and end time not being processes by URBANopt CLI opendss command

### ISSUE THREAD

**Issue by tanushree04** [urbanopt/urbanopt-ditto-reader#32] opened 2022-03-04 18:18 UTC
On adding the start and end time to the opendss command, an error is being thrown in windows for an extra time argument.

**Comment by tarekelgindy** [comment] 2022-03-11 06:39
Do you have example output for this?
If I was to guess I'd say it's because the path to the opendss_folder parameter in the config is pointing to the incorrect location

**Comment by vtnate** [comment] 2022-04-11 14:52
This is a duplicate of #26 which has been resolved in the urbanopt cli. Closing this ticket.

**Closed as completed by vtnate** 2022-04-11 14:52 UTC
